[package]
name = "s3k-common"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfield-struct = { git = "https://github.com/Dr-TSNG/bitfield-struct-rs" }
bitflags = "2.10"
num_enum = { version = "0.7", default-features = false }
buddy_system_allocator = { version = "0.11", optional = true }

[features]
alloc = ["dep:buddy_system_allocator"]
qemu_virt = []
qemu_virt4 = []
sifive_unleashed = []
sifive_unleashed4 = []
